services:
  hyper-hdr:
    container_name: hyper-hdr
    image: gpregger/hyperhdr:latest
    ports:
      - '12000:8090'  # WebUI
      - '12444:19444' # JSON Server (remote control)
      - '12400:19400' # Flatbuffers server
    devices:
      - /dev/video0:/dev/video0
    environment:
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000

    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/root:/root/.hyperhdr
    restart: unless-stopped
