services:
  hyper-hdr:
    container_name: hyper-hdr
    image: nocturno/hyper-hdr:latest
    ports:
      - '12000:8090'  # WebUI
      - '12444:19444' # JSON Server (remote control)
      - '12400:19400' # Flatbuffers server
    devices: 
      - /dev/wled:/dev/wled
    environment:
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/config:/config
    restart: unless-stopped
