services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:5 # images are also available on docker hub: seriousm4x/upsnap:5
    network_mode: host
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/upsnap:/app/pb_data
    ports:
      - 8990:8990
    # # To use a non-root user, create the mountpoint first (mkdir data) so that it has the right permission.
    # user: 1000:1000
    environment:
       - TZ=Europe/Berlin # Set container timezone for cron schedules
       - UPSNAP_HTTP_LISTEN=umbrel.local:8990
